# Required
version: 2

# Image to use
build:
  os: ubuntu-20.04
  image: testing

# Configuration
python:
  version: 3.11
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
